# run
# conda env create -f env.yml
name: heroku_app
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - scikit-learn
  - requests
  - uvicorn
  - gunicorn
  - pytest
  - fastapi=0.63.0
  - jupyter
  - dvc
  - awscli=1.22.12
  - python=3.8